import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    home: "Home",
    myTrips: "My Trips",
    createTrip: "Create Trip",
    aiRecommendations: "AI Recommendations",
    profile: "Profile",
    logout: "Logout",
    
    // General
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    clear: "Clear",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    join: "Join Trip",
    leave: "Leave Trip",
    share: "Share",
    loading: "Loading...",
    noResults: "No results found",
    
    // Trip details
    tripDetails: "Trip Details",
    organizer: "Organizer",
    participants: "Participants",
    maxParticipants: "Max Participants",
    date: "Date",
    duration: "Duration",
    difficulty: "Difficulty",
    trailType: "Trail Type",
    interests: "Interests",
    petsAllowed: "Pets Allowed",
    campingAvailable: "Camping Available",
    weather: "Weather Forecast",
    location: "Location",
    region: "Region",
    
    // Duration types
    hours: "Hours",
    half_day: "Half Day",
    full_day: "Full Day",
    overnight: "Overnight",
    multi_day: "Multi-Day",
    
    // Difficulty levels
    easy: "Easy",
    moderate: "Moderate",
    challenging: "Challenging",
    hard: "Hard",
    extreme: "Extreme",
    
    // Trail types
    water: "Water Trail",
    full_shade: "Full Shade",
    partial_shade: "Partial Shade",
    desert: "Desert",
    forest: "Forest",
    coastal: "Coastal",
    mountain: "Mountain",
    historical: "Historical",
    urban: "Urban",

    // Activity types
    hiking: "Hiking",
    cycling: "Cycling",
    offroad: "Off-Road",
    activityType: "Activity Type",

    // Cycling types
    road: "Road Cycling",
    gravel: "Gravel",
    hybrid: "Hybrid",
    bmx: "BMX",
    electric: "Electric Bike",
    cyclingType: "Cycling Type",
    cyclingDistance: "Distance (km)",
    cyclingElevation: "Elevation Gain (m)",

    // Off-road types
    jeep: "Jeep",
    atv: "ATV / Quad",
    dirt_bike: "Dirt Bike",
    side_by_side: "Side by Side / UTV",
    buggy: "Buggy",
    truck: "4x4 Truck",
    offroadVehicleType: "Vehicle Type",
    offroadDistance: "Distance (km)",
    offroadTerrainType: "Terrain Types",

    // Terrain types
    sand: "Sand Dunes",
    rocks: "Rocky Terrain",
    mud: "Mud",
    hills: "Hills & Slopes",
    forest_trails: "Forest Trails",
    river_crossing: "River Crossing",
    
    // Interests
    nature: "Nature",
    history: "History",
    photography: "Photography",
    birdwatching: "Birdwatching",
    archaeology: "Archaeology",
    geology: "Geology",
    botany: "Botany",
    extreme_sports: "Extreme Sports",
    family_friendly: "Family Friendly",
    romantic: "Romantic",
    
    // Countries
    country: "Country",
    selectCountry: "Select Country",
    israel: "Israel",
    usa: "United States",
    italy: "Italy",
    spain: "Spain",
    france: "France",
    germany: "Germany",
    uk: "United Kingdom",
    japan: "Japan",
    australia: "Australia",
    canada: "Canada",
    switzerland: "Switzerland",
    austria: "Austria",
    new_zealand: "New Zealand",
    norway: "Norway",
    sweden: "Sweden",
    greece: "Greece",
    portugal: "Portugal",
    netherlands: "Netherlands",
    belgium: "Belgium",
    denmark: "Denmark",
    ireland: "Ireland",
    iceland: "Iceland",
    croatia: "Croatia",
    poland: "Poland",
    czech_republic: "Czech Republic",
    thailand: "Thailand",
    indonesia: "Indonesia",
    malaysia: "Malaysia",
    vietnam: "Vietnam",
    south_korea: "South Korea",
    china: "China",
    india: "India",
    nepal: "Nepal",
    turkey: "Turkey",
    egypt: "Egypt",
    morocco: "Morocco",
    south_africa: "South Africa",
    kenya: "Kenya",
    tanzania: "Tanzania",
    brazil: "Brazil",
    argentina: "Argentina",
    chile: "Chile",
    peru: "Peru",
    mexico: "Mexico",
    costa_rica: "Costa Rica",
    finland: "Finland",
    romania: "Romania",
    hungary: "Hungary",
    slovakia: "Slovakia",
    bulgaria: "Bulgaria",
    serbia: "Serbia",
    slovenia: "Slovenia",
    montenegro: "Montenegro",
    bosnia_herzegovina: "Bosnia & Herzegovina",
    albania: "Albania",
    north_macedonia: "North Macedonia",
    luxembourg: "Luxembourg",
    malta: "Malta",
    cyprus: "Cyprus",
    estonia: "Estonia",
    latvia: "Latvia",
    lithuania: "Lithuania",

    // Regions - Israel
    north: "North",
    center: "Center",
    south: "South",
    jerusalem: "Jerusalem Area",
    negev: "Negev",
    eilat: "Eilat Area",

    // Status
    open: "Open",
    full: "Full",
    completed: "Completed",
    cancelled: "Cancelled",
    
    // Form labels
    titleHe: "Title (Hebrew)",
    titleEn: "Title (English)",
    descriptionHe: "Description (Hebrew)",
    descriptionEn: "Description (English)",
    selectDate: "Select Date",
    selectRegion: "Select Region",
    selectDifficulty: "Select Difficulty",
    selectDuration: "Select Duration",
    durationValue: "Duration Value",
    parentAgeRange: "Parent Age Range",
    childrenAgeRange: "Children Age Range",
    minAge: "Min Age",
    maxAge: "Max Age",
    uploadImage: "Upload Image",
    
    // Messages
    tripCreated: "Trip created successfully!",
    tripUpdated: "Trip updated successfully!",
    joinedTrip: "You have joined the trip!",
    leftTrip: "You have left the trip!",
    tripFull: "This trip is full",
    alreadyJoined: "You have already joined this trip",
    
    // AI
    getRecommendations: "Get AI Recommendations",
    basedOnLocation: "Based on your location",
    basedOnPreferences: "Based on your preferences",
    recommendedTrips: "Recommended Trips for You",
    
    // Weather
    temperature: "Temperature",
    humidity: "Humidity",
    wind: "Wind",
    conditions: "Conditions",
    
    // Yes/No
    yes: "Yes",
    no: "No",
    
    // Filters
    allRegions: "All Regions",
    allDifficulties: "All Difficulties",
    allDurations: "All Durations",
    dateRange: "Date Range",
    from: "From",
    to: "To",

    // Accessibility
    wheelchair: "Wheelchair Accessible",
    visual_impairment: "Visual Impairment",
    hearing_impairment: "Hearing Impairment",
    mobility_aid: "Mobility Aid",
    stroller_friendly: "Stroller Friendly",
    elderly_friendly: "Elderly Friendly",
    accessibilityTypes: "Accessibility Types",
    myAccessibilityNeeds: "My Accessibility Needs",
    
    // Hero
    heroTitle: "Find Trip Partners",
    heroSubtitle: "Join organized groups or create your own trip and invite others",
    exploreTrips: "Explore Trips",
    savedTrips: "Saved Trips",

    // Empty states
    noTripsFound: "No trips found",
    noSavedTrips: "No saved trips yet",
    createFirstTrip: "Create your first trip",
    noUpcomingTrips: "No upcoming trips",
    noOrganizedTrips: "No organized trips yet",

    // Budget
    budget: "Budget",
    comfortable: "Comfortable",
    luxury: "Luxury",

    // Travel companions
    solo: "Solo",
    couple: "Couple",
    family_young_kids: "Family (Young Kids)",
    family_teens: "Family (Teens)",
    friends: "Friends",
    group: "Group",

    // Activity intensity
    relaxed: "Relaxed",
    active: "Active",
    very_active: "Very Active",

    // Accommodation
    accommodation: "Accommodation",
    camping: "Camping",
    hostel: "Hostel",
    hotel: "Hotel",
    boutique: "Boutique Hotel",
    resort: "Resort",
    vacation_rental: "Vacation Rental",
  },
  he: {
    // Navigation
    home: "בית",
    myTrips: "הטיולים שלי",
    createTrip: "צור טיול",
    aiRecommendations: "המלצות AI",
    profile: "פרופיל",
    logout: "התנתק",
    
    // General
    search: "חיפוש",
    filter: "סינון",
    apply: "החל",
    clear: "נקה",
    save: "שמור",
    cancel: "ביטול",
    delete: "מחק",
    edit: "ערוך",
    join: "הצטרף לטיול",
    leave: "עזוב טיול",
    share: "שתף",
    loading: "טוען...",
    noResults: "לא נמצאו תוצאות",
    
    // Trip details
    tripDetails: "פרטי הטיול",
    organizer: "מארגן",
    participants: "משתתפים",
    maxParticipants: "מקסימום משתתפים",
    date: "תאריך",
    duration: "משך",
    difficulty: "רמת קושי",
    trailType: "סוג מסלול",
    interests: "תחומי עניין",
    petsAllowed: "מותר בעלי חיים",
    campingAvailable: "אפשרות קמפינג",
    weather: "תחזית מזג האוויר",
    location: "מיקום",
    region: "אזור",
    
    // Duration types
    hours: "שעות",
    half_day: "חצי יום",
    full_day: "יום מלא",
    overnight: "לילה",
    multi_day: "מספר ימים",
    
    // Difficulty levels
    easy: "קל",
    moderate: "בינוני",
    challenging: "מאתגר",
    hard: "קשה",
    extreme: "אקסטרים",
    
    // Trail types
    water: "מסלול מים",
    full_shade: "מוצל מלא",
    partial_shade: "מוצל חלקי",
    desert: "מדבר",
    forest: "יער",
    coastal: "חופי",
    mountain: "הרים",
    historical: "היסטורי",
    urban: "עירוני",

    // Activity types
    hiking: "טיול רגלי",
    cycling: "רכיבת אופניים",
    offroad: "טיול שטח",
    activityType: "סוג פעילות",

    // Cycling types
    road: "אופני כביש",
    gravel: "גראבל",
    hybrid: "היברידי",
    bmx: "BMX",
    electric: "אופניים חשמליים",
    cyclingType: "סוג אופניים",
    cyclingDistance: "מרחק (ק\"מ)",
    cyclingElevation: "עליה מצטברת (מ')",

    // Off-road types
    jeep: "ג'יפ",
    atv: "טרקטורון",
    dirt_bike: "אופנוע שטח",
    side_by_side: "טרקטורון דו-מושבי",
    buggy: "באגי",
    truck: "רכב שטח 4X4",
    offroadVehicleType: "סוג רכב",
    offroadDistance: "מרחק (ק\"מ)",
    offroadTerrainType: "סוגי שטח",

    // Terrain types
    sand: "דיונות חול",
    rocks: "סלעים",
    mud: "בוץ",
    hills: "גבעות ומדרונות",
    forest_trails: "שבילי יער",
    river_crossing: "חציית נחלים",
    
    // Interests
    nature: "טבע",
    history: "היסטוריה",
    photography: "צילום",
    birdwatching: "צפרות",
    archaeology: "ארכיאולוגיה",
    geology: "גיאולוגיה",
    botany: "בוטניקה",
    extreme_sports: "ספורט אתגרי",
    family_friendly: "מתאים למשפחות",
    romantic: "רומנטי",
    
    // Countries
    country: "מדינה",
    selectCountry: "בחר מדינה",
    israel: "ישראל",
    usa: "ארצות הברית",
    italy: "איטליה",
    spain: "ספרד",
    france: "צרפת",
    germany: "גרמניה",
    uk: "בריטניה",
    japan: "יפן",
    australia: "אוסטרליה",
    canada: "קנדה",
    switzerland: "שוויץ",
    austria: "אוסטריה",
    new_zealand: "ניו זילנד",
    norway: "נורווגיה",
    sweden: "שוודיה",
    greece: "יוון",
    portugal: "פורטוגל",
    netherlands: "הולנד",
    belgium: "בלגיה",
    denmark: "דנמרק",
    ireland: "אירלנד",
    iceland: "איסלנד",
    croatia: "קרואטיה",
    poland: "פולין",
    czech_republic: "צ'כיה",
    thailand: "תאילנד",
    indonesia: "אינדונזיה",
    malaysia: "מלזיה",
    vietnam: "וייטנאם",
    south_korea: "דרום קוריאה",
    china: "סין",
    india: "הודו",
    nepal: "נפאל",
    turkey: "טורקיה",
    egypt: "מצרים",
    morocco: "מרוקו",
    south_africa: "דרום אפריקה",
    kenya: "קניה",
    tanzania: "טנזניה",
    brazil: "ברזיל",
    argentina: "ארגנטינה",
    chile: "צ'ילה",
    peru: "פרו",
    mexico: "מקסיקו",
    costa_rica: "קוסטה ריקה",
    finland: "פינלנד",
    romania: "רומניה",
    hungary: "הונגריה",
    slovakia: "סלובקיה",
    bulgaria: "בולגריה",
    serbia: "סרביה",
    slovenia: "סלובניה",
    montenegro: "מונטנגרו",
    bosnia_herzegovina: "בוסניה והרצגובינה",
    albania: "אלבניה",
    north_macedonia: "מקדוניה הצפונית",
    luxembourg: "לוקסמבורג",
    malta: "מלטה",
    cyprus: "קפריסין",
    estonia: "אסטוניה",
    latvia: "לטביה",
    lithuania: "ליטא",

    // Regions - Israel
    north: "צפון",
    center: "מרכז",
    south: "דרום",
    jerusalem: "אזור ירושלים",
    negev: "נגב",
    eilat: "אזור אילת",
    
    // Status
    open: "פתוח",
    full: "מלא",
    completed: "הושלם",
    cancelled: "בוטל",
    
    // Form labels
    titleHe: "כותרת (עברית)",
    titleEn: "כותרת (אנגלית)",
    descriptionHe: "תיאור (עברית)",
    descriptionEn: "תיאור (אנגלית)",
    selectDate: "בחר תאריך",
    selectRegion: "בחר אזור",
    selectDifficulty: "בחר רמת קושי",
    selectDuration: "בחר משך",
    durationValue: "משך זמן",
    parentAgeRange: "טווח גילאי הורים",
    childrenAgeRange: "טווח גילאי ילדים",
    minAge: "גיל מינימלי",
    maxAge: "גיל מקסימלי",
    uploadImage: "העלה תמונה",
    
    // Messages
    tripCreated: "הטיול נוצר בהצלחה!",
    tripUpdated: "הטיול עודכן בהצלחה!",
    joinedTrip: "הצטרפת לטיול!",
    leftTrip: "עזבת את הטיול!",
    tripFull: "הטיול מלא",
    alreadyJoined: "כבר הצטרפת לטיול הזה",
    
    // AI
    getRecommendations: "קבל המלצות AI",
    basedOnLocation: "מבוסס על המיקום שלך",
    basedOnPreferences: "מבוסס על ההעדפות שלך",
    recommendedTrips: "טיולים מומלצים עבורך",
    
    // Weather
    temperature: "טמפרטורה",
    humidity: "לחות",
    wind: "רוח",
    conditions: "מצב",
    
    // Yes/No
    yes: "כן",
    no: "לא",
    
    // Filters
    allRegions: "כל האזורים",
    allDifficulties: "כל רמות הקושי",
    allDurations: "כל משכי הזמן",
    dateRange: "טווח תאריכים",
    from: "מ",
    to: "עד",

    // Accessibility
    wheelchair: "נגיש לכיסא גלגלים",
    visual_impairment: "לקות ראייה",
    hearing_impairment: "לקות שמיעה",
    mobility_aid: "עזרי ניידות",
    stroller_friendly: "ידידותי לעגלות",
    elderly_friendly: "ידידותי לקשישים",
    accessibilityTypes: "סוגי נגישות",
    myAccessibilityNeeds: "דרישות הנגישות שלי",
    
    // Hero
    heroTitle: "מצאו שותפים לטיול",
    heroSubtitle: "הצטרפו לקבוצות מאורגנות או צרו טיול משלכם והזמינו אחרים",
    exploreTrips: "גלה טיולים",
    savedTrips: "טיולים שמורים",

    // Empty states
    noTripsFound: "לא נמצאו טיולים",
    noSavedTrips: "אין טיולים שמורים עדיין",
    createFirstTrip: "צור את הטיול הראשון שלך",
    noUpcomingTrips: "אין טיולים קרובים",
    noOrganizedTrips: "עדיין אין טיולים שארגנת",

    // Budget
    budget: "חסכוני",
    comfortable: "נוח",
    luxury: "יוקרתי",

    // Travel companions
    solo: "סולו",
    couple: "זוג",
    family_young_kids: "משפחה (ילדים קטנים)",
    family_teens: "משפחה (מתבגרים)",
    friends: "חברים",
    group: "קבוצה",

    // Activity intensity
    relaxed: "נינוח",
    active: "פעיל",
    very_active: "פעיל מאוד",

    // Accommodation
    accommodation: "לינה",
    camping: "קמפינג",
    hostel: "אכסניה",
    hotel: "מלון",
    boutique: "מלון בוטיק",
    resort: "אתר נופש",
    vacation_rental: "דירת נופש",
  },
  fr: {
    home: "Accueil",
    myTrips: "Mes Voyages",
    createTrip: "Créer",
    aiRecommendations: "IA",
    profile: "Profil",
    logout: "Déconnexion",
    search: "Rechercher",
    filter: "Filtrer",
    apply: "Appliquer",
    clear: "Effacer",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    join: "Rejoindre",
    leave: "Quitter",
    share: "Partager",
    loading: "Chargement...",
    noResults: "Aucun résultat",
    tripDetails: "Détails",
    organizer: "Organisateur",
    participants: "Participants",
    maxParticipants: "Max",
    date: "Date",
    duration: "Durée",
    difficulty: "Difficulté",
    trailType: "Type",
    interests: "Intérêts",
    petsAllowed: "Animaux OK",
    campingAvailable: "Camping",
    weather: "Météo",
    location: "Lieu",
    region: "Région",
    hours: "Heures",
    half_day: "Demi-journée",
    full_day: "Journée",
    overnight: "Nuit",
    multi_day: "Plusieurs jours",
    easy: "Facile",
    moderate: "Modéré",
    challenging: "Difficile",
    hard: "Très difficile",
    extreme: "Extrême",
    water: "Aquatique",
    full_shade: "Ombragé",
    partial_shade: "Mi-ombre",
    desert: "Désert",
    forest: "Forêt",
    coastal: "Côtier",
    mountain: "Montagne",
    historical: "Historique",
    urban: "Urbain",
    hiking: "Randonnée",
    cycling: "Cyclisme",
    offroad: "Tout-terrain",
    activityType: "Activité",
    road: "Route",
    gravel: "Gravel",
    hybrid: "Hybride",
    bmx: "BMX",
    electric: "Électrique",
    cyclingType: "Type vélo",
    cyclingDistance: "Distance",
    cyclingElevation: "Dénivelé",
    jeep: "Jeep",
    atv: "Quad",
    dirt_bike: "Moto cross",
    side_by_side: "SSV",
    buggy: "Buggy",
    truck: "4x4",
    offroadVehicleType: "Véhicule",
    offroadDistance: "Distance",
    offroadTerrainType: "Terrain",
    sand: "Sable",
    rocks: "Rochers",
    mud: "Boue",
    hills: "Collines",
    forest_trails: "Sentiers",
    river_crossing: "Rivière",
    nature: "Nature",
    history: "Histoire",
    photography: "Photo",
    birdwatching: "Oiseaux",
    archaeology: "Archéologie",
    geology: "Géologie",
    botany: "Botanique",
    extreme_sports: "Extrême",
    family_friendly: "Familial",
    romantic: "Romantique",
    country: "Pays",
    selectCountry: "Pays",
    israel: "Israël",
    usa: "États-Unis",
    italy: "Italie",
    spain: "Espagne",
    france: "France",
    germany: "Allemagne",
    uk: "Royaume-Uni",
    japan: "Japon",
    australia: "Australie",
    canada: "Canada",
    switzerland: "Suisse",
    austria: "Autriche",
    new_zealand: "Nouvelle-Zélande",
    norway: "Norvège",
    sweden: "Suède",
    greece: "Grèce",
    portugal: "Portugal",
    netherlands: "Pays-Bas",
    belgium: "Belgique",
    denmark: "Danemark",
    ireland: "Irlande",
    iceland: "Islande",
    croatia: "Croatie",
    poland: "Pologne",
    czech_republic: "Tchéquie",
    thailand: "Thaïlande",
    indonesia: "Indonésie",
    malaysia: "Malaisie",
    vietnam: "Vietnam",
    south_korea: "Corée du Sud",
    china: "Chine",
    india: "Inde",
    nepal: "Népal",
    turkey: "Turquie",
    egypt: "Égypte",
    morocco: "Maroc",
    south_africa: "Afrique du Sud",
    kenya: "Kenya",
    tanzania: "Tanzanie",
    brazil: "Brésil",
    argentina: "Argentine",
    chile: "Chili",
    peru: "Pérou",
    mexico: "Mexique",
    costa_rica: "Costa Rica",
    finland: "Finlande",
    romania: "Roumanie",
    hungary: "Hongrie",
    slovakia: "Slovaquie",
    bulgaria: "Bulgarie",
    serbia: "Serbie",
    slovenia: "Slovénie",
    montenegro: "Monténégro",
    bosnia_herzegovina: "Bosnie",
    albania: "Albanie",
    north_macedonia: "Macédoine",
    luxembourg: "Luxembourg",
    malta: "Malte",
    cyprus: "Chypre",
    estonia: "Estonie",
    latvia: "Lettonie",
    lithuania: "Lituanie",
    north: "Nord",
    center: "Centre",
    south: "Sud",
    jerusalem: "Jérusalem",
    negev: "Néguev",
    eilat: "Eilat",
    open: "Ouvert",
    full: "Complet",
    completed: "Terminé",
    cancelled: "Annulé",
    titleHe: "Titre (HE)",
    titleEn: "Titre (EN)",
    descriptionHe: "Description (HE)",
    descriptionEn: "Description (EN)",
    selectDate: "Date",
    selectRegion: "Région",
    selectDifficulty: "Difficulté",
    selectDuration: "Durée",
    durationValue: "Valeur",
    parentAgeRange: "Âge parents",
    childrenAgeRange: "Âge enfants",
    minAge: "Min",
    maxAge: "Max",
    uploadImage: "Image",
    tripCreated: "Créé!",
    tripUpdated: "Mis à jour!",
    joinedTrip: "Rejoint!",
    leftTrip: "Quitté!",
    tripFull: "Complet",
    alreadyJoined: "Déjà rejoint",
    getRecommendations: "Recommandations",
    basedOnLocation: "Selon position",
    basedOnPreferences: "Selon préférences",
    recommendedTrips: "Recommandés",
    temperature: "Température",
    humidity: "Humidité",
    wind: "Vent",
    conditions: "Conditions",
    yes: "Oui",
    no: "Non",
    allRegions: "Toutes",
    allDifficulties: "Toutes",
    allDurations: "Toutes",
    dateRange: "Dates",
    from: "De",
    to: "À",
    wheelchair: "Fauteuil",
    visual_impairment: "Vue",
    hearing_impairment: "Ouïe",
    mobility_aid: "Mobilité",
    stroller_friendly: "Poussette",
    elderly_friendly: "Seniors",
    accessibilityTypes: "Accessibilité",
    myAccessibilityNeeds: "Mes besoins",
    heroTitle: "Partenaires",
    heroSubtitle: "Rejoignez ou créez",
    exploreTrips: "Explorer",
    savedTrips: "Sauvegardés",
    noTripsFound: "Aucun",
    noSavedTrips: "Aucun sauvegardé",
    createFirstTrip: "Créer",
    noUpcomingTrips: "Aucun",
    noOrganizedTrips: "Aucun",
    budget: "Économique",
    comfortable: "Confortable",
    luxury: "Luxe",
    solo: "Solo",
    couple: "Couple",
    family_young_kids: "Famille",
    family_teens: "Famille",
    friends: "Amis",
    group: "Groupe",
    relaxed: "Détendu",
    active: "Actif",
    very_active: "Très actif",
    accommodation: "Logement",
    camping: "Camping",
    hostel: "Auberge",
    hotel: "Hôtel",
    boutique: "Boutique",
    resort: "Resort",
    vacation_rental: "Location",
  },
  es: {
    home: "Inicio",
    myTrips: "Mis Viajes",
    createTrip: "Crear",
    aiRecommendations: "IA",
    profile: "Perfil",
    logout: "Salir",
    search: "Buscar",
    filter: "Filtrar",
    apply: "Aplicar",
    clear: "Limpiar",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    join: "Unirse",
    leave: "Salir",
    share: "Compartir",
    loading: "Cargando...",
    noResults: "Sin resultados",
    tripDetails: "Detalles",
    organizer: "Organizador",
    participants: "Participantes",
    maxParticipants: "Máx",
    date: "Fecha",
    duration: "Duración",
    difficulty: "Dificultad",
    trailType: "Tipo",
    interests: "Intereses",
    petsAllowed: "Mascotas",
    campingAvailable: "Camping",
    weather: "Clima",
    location: "Ubicación",
    region: "Región",
    hours: "Horas",
    half_day: "Medio día",
    full_day: "Día",
    overnight: "Noche",
    multi_day: "Varios días",
    easy: "Fácil",
    moderate: "Moderado",
    challenging: "Desafiante",
    hard: "Difícil",
    extreme: "Extremo",
    water: "Agua",
    full_shade: "Sombra",
    partial_shade: "Semi-sombra",
    desert: "Desierto",
    forest: "Bosque",
    coastal: "Costa",
    mountain: "Montaña",
    historical: "Histórico",
    urban: "Urbano",
    hiking: "Senderismo",
    cycling: "Ciclismo",
    offroad: "Todo terreno",
    activityType: "Actividad",
    road: "Carretera",
    gravel: "Grava",
    hybrid: "Híbrido",
    bmx: "BMX",
    electric: "Eléctrico",
    cyclingType: "Tipo bici",
    cyclingDistance: "Distancia",
    cyclingElevation: "Desnivel",
    jeep: "Jeep",
    atv: "Cuatrimoto",
    dirt_bike: "Moto cross",
    side_by_side: "UTV",
    buggy: "Buggy",
    truck: "4x4",
    offroadVehicleType: "Vehículo",
    offroadDistance: "Distancia",
    offroadTerrainType: "Terreno",
    sand: "Arena",
    rocks: "Rocas",
    mud: "Barro",
    hills: "Colinas",
    forest_trails: "Senderos",
    river_crossing: "Río",
    nature: "Naturaleza",
    history: "Historia",
    photography: "Foto",
    birdwatching: "Aves",
    archaeology: "Arqueología",
    geology: "Geología",
    botany: "Botánica",
    extreme_sports: "Extremo",
    family_friendly: "Familiar",
    romantic: "Romántico",
    country: "País",
    selectCountry: "País",
    israel: "Israel",
    usa: "EE.UU.",
    italy: "Italia",
    spain: "España",
    france: "Francia",
    germany: "Alemania",
    uk: "Reino Unido",
    japan: "Japón",
    australia: "Australia",
    canada: "Canadá",
    switzerland: "Suiza",
    austria: "Austria",
    new_zealand: "Nueva Zelanda",
    norway: "Noruega",
    sweden: "Suecia",
    greece: "Grecia",
    portugal: "Portugal",
    netherlands: "Países Bajos",
    belgium: "Bélgica",
    denmark: "Dinamarca",
    ireland: "Irlanda",
    iceland: "Islandia",
    croatia: "Croacia",
    poland: "Polonia",
    czech_republic: "Chequia",
    thailand: "Tailandia",
    indonesia: "Indonesia",
    malaysia: "Malasia",
    vietnam: "Vietnam",
    south_korea: "Corea del Sur",
    china: "China",
    india: "India",
    nepal: "Nepal",
    turkey: "Turquía",
    egypt: "Egipto",
    morocco: "Marruecos",
    south_africa: "Sudáfrica",
    kenya: "Kenia",
    tanzania: "Tanzania",
    brazil: "Brasil",
    argentina: "Argentina",
    chile: "Chile",
    peru: "Perú",
    mexico: "México",
    costa_rica: "Costa Rica",
    finland: "Finlandia",
    romania: "Rumania",
    hungary: "Hungría",
    slovakia: "Eslovaquia",
    bulgaria: "Bulgaria",
    serbia: "Serbia",
    slovenia: "Eslovenia",
    montenegro: "Montenegro",
    bosnia_herzegovina: "Bosnia",
    albania: "Albania",
    north_macedonia: "Macedonia",
    luxembourg: "Luxemburgo",
    malta: "Malta",
    cyprus: "Chipre",
    estonia: "Estonia",
    latvia: "Letonia",
    lithuania: "Lituania",
    north: "Norte",
    center: "Centro",
    south: "Sur",
    jerusalem: "Jerusalén",
    negev: "Néguev",
    eilat: "Eilat",
    open: "Abierto",
    full: "Lleno",
    completed: "Completado",
    cancelled: "Cancelado",
    titleHe: "Título (HE)",
    titleEn: "Título (EN)",
    descriptionHe: "Descripción (HE)",
    descriptionEn: "Descripción (EN)",
    selectDate: "Fecha",
    selectRegion: "Región",
    selectDifficulty: "Dificultad",
    selectDuration: "Duración",
    durationValue: "Valor",
    parentAgeRange: "Edad padres",
    childrenAgeRange: "Edad niños",
    minAge: "Mín",
    maxAge: "Máx",
    uploadImage: "Imagen",
    tripCreated: "¡Creado!",
    tripUpdated: "¡Actualizado!",
    joinedTrip: "¡Unido!",
    leftTrip: "¡Salido!",
    tripFull: "Lleno",
    alreadyJoined: "Ya unido",
    getRecommendations: "Recomendaciones",
    basedOnLocation: "Por ubicación",
    basedOnPreferences: "Por preferencias",
    recommendedTrips: "Recomendados",
    temperature: "Temperatura",
    humidity: "Humedad",
    wind: "Viento",
    conditions: "Condiciones",
    yes: "Sí",
    no: "No",
    allRegions: "Todas",
    allDifficulties: "Todas",
    allDurations: "Todas",
    dateRange: "Fechas",
    from: "Desde",
    to: "Hasta",
    wheelchair: "Silla ruedas",
    visual_impairment: "Visual",
    hearing_impairment: "Auditivo",
    mobility_aid: "Movilidad",
    stroller_friendly: "Cochecito",
    elderly_friendly: "Mayores",
    accessibilityTypes: "Accesibilidad",
    myAccessibilityNeeds: "Mis necesidades",
    heroTitle: "Compañeros",
    heroSubtitle: "Únete o crea",
    exploreTrips: "Explorar",
    savedTrips: "Guardados",
    noTripsFound: "Ninguno",
    noSavedTrips: "Sin guardados",
    createFirstTrip: "Crear",
    noUpcomingTrips: "Ninguno",
    noOrganizedTrips: "Ninguno",
    budget: "Económico",
    comfortable: "Cómodo",
    luxury: "Lujo",
    solo: "Solo",
    couple: "Pareja",
    family_young_kids: "Familia",
    family_teens: "Familia",
    friends: "Amigos",
    group: "Grupo",
    relaxed: "Relajado",
    active: "Activo",
    very_active: "Muy activo",
    accommodation: "Alojamiento",
    camping: "Camping",
    hostel: "Hostal",
    hotel: "Hotel",
    boutique: "Boutique",
    resort: "Resort",
    vacation_rental: "Alquiler",
  },
  de: {
    home: "Start",
    myTrips: "Meine Reisen",
    createTrip: "Erstellen",
    aiRecommendations: "KI",
    profile: "Profil",
    logout: "Abmelden",
    search: "Suchen",
    filter: "Filtern",
    apply: "Anwenden",
    clear: "Löschen",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    join: "Beitreten",
    leave: "Verlassen",
    share: "Teilen",
    loading: "Lädt...",
    noResults: "Keine Ergebnisse",
    tripDetails: "Details",
    organizer: "Organisator",
    participants: "Teilnehmer",
    maxParticipants: "Max",
    date: "Datum",
    duration: "Dauer",
    difficulty: "Schwierigkeit",
    trailType: "Typ",
    interests: "Interessen",
    petsAllowed: "Haustiere",
    campingAvailable: "Camping",
    weather: "Wetter",
    location: "Ort",
    region: "Region",
    hours: "Stunden",
    half_day: "Halbtag",
    full_day: "Tag",
    overnight: "Nacht",
    multi_day: "Mehrtägig",
    easy: "Leicht",
    moderate: "Mäßig",
    challenging: "Fordernd",
    hard: "Schwer",
    extreme: "Extrem",
    water: "Wasser",
    full_shade: "Schatten",
    partial_shade: "Halbschatten",
    desert: "Wüste",
    forest: "Wald",
    coastal: "Küste",
    mountain: "Berg",
    historical: "Historisch",
    urban: "Urban",
    hiking: "Wandern",
    cycling: "Radfahren",
    offroad: "Offroad",
    activityType: "Aktivität",
    road: "Straße",
    gravel: "Gravel",
    hybrid: "Hybrid",
    bmx: "BMX",
    electric: "E-Bike",
    cyclingType: "Radtyp",
    cyclingDistance: "Entfernung",
    cyclingElevation: "Höhenmeter",
    jeep: "Jeep",
    atv: "Quad",
    dirt_bike: "Enduro",
    side_by_side: "UTV",
    buggy: "Buggy",
    truck: "4x4",
    offroadVehicleType: "Fahrzeug",
    offroadDistance: "Entfernung",
    offroadTerrainType: "Gelände",
    sand: "Sand",
    rocks: "Felsen",
    mud: "Schlamm",
    hills: "Hügel",
    forest_trails: "Waldwege",
    river_crossing: "Fluss",
    nature: "Natur",
    history: "Geschichte",
    photography: "Foto",
    birdwatching: "Vögel",
    archaeology: "Archäologie",
    geology: "Geologie",
    botany: "Botanik",
    extreme_sports: "Extrem",
    family_friendly: "Familie",
    romantic: "Romantisch",
    country: "Land",
    selectCountry: "Land",
    israel: "Israel",
    usa: "USA",
    italy: "Italien",
    spain: "Spanien",
    france: "Frankreich",
    germany: "Deutschland",
    uk: "UK",
    japan: "Japan",
    australia: "Australien",
    canada: "Kanada",
    switzerland: "Schweiz",
    austria: "Österreich",
    new_zealand: "Neuseeland",
    norway: "Norwegen",
    sweden: "Schweden",
    greece: "Griechenland",
    portugal: "Portugal",
    netherlands: "Niederlande",
    belgium: "Belgien",
    denmark: "Dänemark",
    ireland: "Irland",
    iceland: "Island",
    croatia: "Kroatien",
    poland: "Polen",
    czech_republic: "Tschechien",
    thailand: "Thailand",
    indonesia: "Indonesien",
    malaysia: "Malaysia",
    vietnam: "Vietnam",
    south_korea: "Südkorea",
    china: "China",
    india: "Indien",
    nepal: "Nepal",
    turkey: "Türkei",
    egypt: "Ägypten",
    morocco: "Marokko",
    south_africa: "Südafrika",
    kenya: "Kenia",
    tanzania: "Tansania",
    brazil: "Brasilien",
    argentina: "Argentinien",
    chile: "Chile",
    peru: "Peru",
    mexico: "Mexiko",
    costa_rica: "Costa Rica",
    finland: "Finnland",
    romania: "Rumänien",
    hungary: "Ungarn",
    slovakia: "Slowakei",
    bulgaria: "Bulgarien",
    serbia: "Serbien",
    slovenia: "Slowenien",
    montenegro: "Montenegro",
    bosnia_herzegovina: "Bosnien",
    albania: "Albanien",
    north_macedonia: "Mazedonien",
    luxembourg: "Luxemburg",
    malta: "Malta",
    cyprus: "Zypern",
    estonia: "Estland",
    latvia: "Lettland",
    lithuania: "Litauen",
    north: "Norden",
    center: "Mitte",
    south: "Süden",
    jerusalem: "Jerusalem",
    negev: "Negev",
    eilat: "Eilat",
    open: "Offen",
    full: "Voll",
    completed: "Fertig",
    cancelled: "Abgesagt",
    titleHe: "Titel (HE)",
    titleEn: "Titel (EN)",
    descriptionHe: "Beschreibung (HE)",
    descriptionEn: "Beschreibung (EN)",
    selectDate: "Datum",
    selectRegion: "Region",
    selectDifficulty: "Schwierigkeit",
    selectDuration: "Dauer",
    durationValue: "Wert",
    parentAgeRange: "Alter Eltern",
    childrenAgeRange: "Alter Kinder",
    minAge: "Min",
    maxAge: "Max",
    uploadImage: "Bild",
    tripCreated: "Erstellt!",
    tripUpdated: "Aktualisiert!",
    joinedTrip: "Beigetreten!",
    leftTrip: "Verlassen!",
    tripFull: "Voll",
    alreadyJoined: "Bereits dabei",
    getRecommendations: "Empfehlungen",
    basedOnLocation: "Nach Standort",
    basedOnPreferences: "Nach Vorlieben",
    recommendedTrips: "Empfohlen",
    temperature: "Temperatur",
    humidity: "Feuchtigkeit",
    wind: "Wind",
    conditions: "Bedingungen",
    yes: "Ja",
    no: "Nein",
    allRegions: "Alle",
    allDifficulties: "Alle",
    allDurations: "Alle",
    dateRange: "Datum",
    from: "Von",
    to: "Bis",
    wheelchair: "Rollstuhl",
    visual_impairment: "Sehbehinderung",
    hearing_impairment: "Hörbehinderung",
    mobility_aid: "Mobilitätshilfe",
    stroller_friendly: "Kinderwagen",
    elderly_friendly: "Senioren",
    accessibilityTypes: "Barrierefreiheit",
    myAccessibilityNeeds: "Meine Bedürfnisse",
    heroTitle: "Partner",
    heroSubtitle: "Beitreten oder erstellen",
    exploreTrips: "Erkunden",
    savedTrips: "Gespeichert",
    noTripsFound: "Keine",
    noSavedTrips: "Keine gespeichert",
    createFirstTrip: "Erstellen",
    noUpcomingTrips: "Keine",
    noOrganizedTrips: "Keine",
    budget: "Budget",
    comfortable: "Komfortabel",
    luxury: "Luxus",
    solo: "Allein",
    couple: "Paar",
    family_young_kids: "Familie",
    family_teens: "Familie",
    friends: "Freunde",
    group: "Gruppe",
    relaxed: "Entspannt",
    active: "Aktiv",
    very_active: "Sehr aktiv",
    accommodation: "Unterkunft",
    camping: "Camping",
    hostel: "Hostel",
    hotel: "Hotel",
    boutique: "Boutique",
    resort: "Resort",
    vacation_rental: "Ferienwohnung",
  },
  it: {
    home: "Home",
    myTrips: "I Miei",
    createTrip: "Crea",
    aiRecommendations: "IA",
    profile: "Profilo",
    logout: "Esci",
    search: "Cerca",
    filter: "Filtra",
    apply: "Applica",
    clear: "Cancella",
    save: "Salva",
    cancel: "Annulla",
    delete: "Elimina",
    edit: "Modifica",
    join: "Unisciti",
    leave: "Lascia",
    share: "Condividi",
    loading: "Caricamento...",
    noResults: "Nessun risultato",
    tripDetails: "Dettagli",
    organizer: "Organizzatore",
    participants: "Partecipanti",
    maxParticipants: "Max",
    date: "Data",
    duration: "Durata",
    difficulty: "Difficoltà",
    trailType: "Tipo",
    interests: "Interessi",
    petsAllowed: "Animali",
    campingAvailable: "Camping",
    weather: "Meteo",
    location: "Luogo",
    region: "Regione",
    hours: "Ore",
    half_day: "Mezza giornata",
    full_day: "Giorno",
    overnight: "Notte",
    multi_day: "Più giorni",
    easy: "Facile",
    moderate: "Moderato",
    challenging: "Impegnativo",
    hard: "Difficile",
    extreme: "Estremo",
    water: "Acqua",
    full_shade: "Ombra",
    partial_shade: "Semi-ombra",
    desert: "Deserto",
    forest: "Foresta",
    coastal: "Costa",
    mountain: "Montagna",
    historical: "Storico",
    urban: "Urbano",
    hiking: "Escursione",
    cycling: "Ciclismo",
    offroad: "Fuoristrada",
    activityType: "Attività",
    road: "Strada",
    gravel: "Gravel",
    hybrid: "Ibrida",
    bmx: "BMX",
    electric: "Elettrica",
    cyclingType: "Tipo bici",
    cyclingDistance: "Distanza",
    cyclingElevation: "Dislivello",
    jeep: "Jeep",
    atv: "Quad",
    dirt_bike: "Moto cross",
    side_by_side: "UTV",
    buggy: "Buggy",
    truck: "4x4",
    offroadVehicleType: "Veicolo",
    offroadDistance: "Distanza",
    offroadTerrainType: "Terreno",
    sand: "Sabbia",
    rocks: "Rocce",
    mud: "Fango",
    hills: "Colline",
    forest_trails: "Sentieri",
    river_crossing: "Fiume",
    nature: "Natura",
    history: "Storia",
    photography: "Foto",
    birdwatching: "Uccelli",
    archaeology: "Archeologia",
    geology: "Geologia",
    botany: "Botanica",
    extreme_sports: "Estremo",
    family_friendly: "Famiglia",
    romantic: "Romantico",
    country: "Paese",
    selectCountry: "Paese",
    israel: "Israele",
    usa: "USA",
    italy: "Italia",
    spain: "Spagna",
    france: "Francia",
    germany: "Germania",
    uk: "Regno Unito",
    japan: "Giappone",
    australia: "Australia",
    canada: "Canada",
    switzerland: "Svizzera",
    austria: "Austria",
    new_zealand: "Nuova Zelanda",
    norway: "Norvegia",
    sweden: "Svezia",
    greece: "Grecia",
    portugal: "Portogallo",
    netherlands: "Paesi Bassi",
    belgium: "Belgio",
    denmark: "Danimarca",
    ireland: "Irlanda",
    iceland: "Islanda",
    croatia: "Croazia",
    poland: "Polonia",
    czech_republic: "Cechia",
    thailand: "Thailandia",
    indonesia: "Indonesia",
    malaysia: "Malesia",
    vietnam: "Vietnam",
    south_korea: "Corea del Sud",
    china: "Cina",
    india: "India",
    nepal: "Nepal",
    turkey: "Turchia",
    egypt: "Egitto",
    morocco: "Marocco",
    south_africa: "Sudafrica",
    kenya: "Kenya",
    tanzania: "Tanzania",
    brazil: "Brasile",
    argentina: "Argentina",
    chile: "Cile",
    peru: "Perù",
    mexico: "Messico",
    costa_rica: "Costa Rica",
    finland: "Finlandia",
    romania: "Romania",
    hungary: "Ungheria",
    slovakia: "Slovacchia",
    bulgaria: "Bulgaria",
    serbia: "Serbia",
    slovenia: "Slovenia",
    montenegro: "Montenegro",
    bosnia_herzegovina: "Bosnia",
    albania: "Albania",
    north_macedonia: "Macedonia",
    luxembourg: "Lussemburgo",
    malta: "Malta",
    cyprus: "Cipro",
    estonia: "Estonia",
    latvia: "Lettonia",
    lithuania: "Lituania",
    north: "Nord",
    center: "Centro",
    south: "Sud",
    jerusalem: "Gerusalemme",
    negev: "Negev",
    eilat: "Eilat",
    open: "Aperto",
    full: "Pieno",
    completed: "Completato",
    cancelled: "Annullato",
    titleHe: "Titolo (HE)",
    titleEn: "Titolo (EN)",
    descriptionHe: "Descrizione (HE)",
    descriptionEn: "Descrizione (EN)",
    selectDate: "Data",
    selectRegion: "Regione",
    selectDifficulty: "Difficoltà",
    selectDuration: "Durata",
    durationValue: "Valore",
    parentAgeRange: "Età genitori",
    childrenAgeRange: "Età bambini",
    minAge: "Min",
    maxAge: "Max",
    uploadImage: "Immagine",
    tripCreated: "Creato!",
    tripUpdated: "Aggiornato!",
    joinedTrip: "Unito!",
    leftTrip: "Lasciato!",
    tripFull: "Pieno",
    alreadyJoined: "Già unito",
    getRecommendations: "Raccomandazioni",
    basedOnLocation: "Per posizione",
    basedOnPreferences: "Per preferenze",
    recommendedTrips: "Raccomandati",
    temperature: "Temperatura",
    humidity: "Umidità",
    wind: "Vento",
    conditions: "Condizioni",
    yes: "Sì",
    no: "No",
    allRegions: "Tutte",
    allDifficulties: "Tutte",
    allDurations: "Tutte",
    dateRange: "Date",
    from: "Da",
    to: "A",
    wheelchair: "Sedia rotelle",
    visual_impairment: "Vista",
    hearing_impairment: "Udito",
    mobility_aid: "Mobilità",
    stroller_friendly: "Passeggino",
    elderly_friendly: "Anziani",
    accessibilityTypes: "Accessibilità",
    myAccessibilityNeeds: "Mie esigenze",
    heroTitle: "Compagni",
    heroSubtitle: "Unisciti o crea",
    exploreTrips: "Esplora",
    savedTrips: "Salvati",
    noTripsFound: "Nessuno",
    noSavedTrips: "Nessuno salvato",
    createFirstTrip: "Crea",
    noUpcomingTrips: "Nessuno",
    noOrganizedTrips: "Nessuno",
    budget: "Economico",
    comfortable: "Comodo",
    luxury: "Lusso",
    solo: "Solo",
    couple: "Coppia",
    family_young_kids: "Famiglia",
    family_teens: "Famiglia",
    friends: "Amici",
    group: "Gruppo",
    relaxed: "Rilassato",
    active: "Attivo",
    very_active: "Molto attivo",
    accommodation: "Alloggio",
    camping: "Campeggio",
    hostel: "Ostello",
    hotel: "Hotel",
    boutique: "Boutique",
    resort: "Resort",
    vacation_rental: "Casa vacanze",
  },
  ru: {
    // Navigation
    home: "Главная",
    myTrips: "Мои поездки",
    createTrip: "Создать",
    aiRecommendations: "AI",
    profile: "Профиль",
    logout: "Выйти",

    // General
    search: "Поиск",
    filter: "Фильтр",
    apply: "Применить",
    clear: "Очистить",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    join: "Присоединиться",
    leave: "Покинуть",
    share: "Поделиться",
    loading: "Загрузка...",
    noResults: "Нет результатов",

    // Trip details
    tripDetails: "Детали",
    organizer: "Организатор",
    participants: "Участники",
    maxParticipants: "Макс",
    date: "Дата",
    duration: "Длительность",
    difficulty: "Сложность",
    trailType: "Тип",
    interests: "Интересы",
    petsAllowed: "Животные",
    campingAvailable: "Кемпинг",
    weather: "Погода",
    location: "Место",
    region: "Регион",

    // Duration types
    hours: "Часы",
    half_day: "Полдня",
    full_day: "День",
    overnight: "Ночь",
    multi_day: "Несколько дней",

    // Difficulty levels
    easy: "Легко",
    moderate: "Средне",
    challenging: "Сложно",
    hard: "Трудно",
    extreme: "Экстрим",

    // Trail types
    water: "Вода",
    full_shade: "Тень",
    partial_shade: "Полутень",
    desert: "Пустыня",
    forest: "Лес",
    coastal: "Побережье",
    mountain: "Горы",
    historical: "Исторический",
    urban: "Городской",

    // Activity types
    hiking: "Пеший",
    cycling: "Велосипед",
    offroad: "Внедорожник",
    activityType: "Активность",

    // Cycling types
    road: "Шоссе",
    gravel: "Гравий",
    hybrid: "Гибрид",
    bmx: "BMX",
    electric: "Электро",
    cyclingType: "Тип велосипеда",
    cyclingDistance: "Расстояние",
    cyclingElevation: "Набор высоты",

    // Off-road types
    jeep: "Джип",
    atv: "Квадроцикл",
    dirt_bike: "Мотокросс",
    side_by_side: "UTV",
    buggy: "Багги",
    truck: "4x4",
    offroadVehicleType: "Транспорт",
    offroadDistance: "Расстояние",
    offroadTerrainType: "Местность",

    // Terrain types
    sand: "Песок",
    rocks: "Камни",
    mud: "Грязь",
    hills: "Холмы",
    forest_trails: "Тропы",
    river_crossing: "Река",

    // Interests
    nature: "Природа",
    history: "История",
    photography: "Фото",
    birdwatching: "Птицы",
    archaeology: "Археология",
    geology: "Геология",
    botany: "Ботаника",
    extreme_sports: "Экстрим",
    family_friendly: "Семья",
    romantic: "Романтика",

    // Countries
    country: "Страна",
    selectCountry: "Страна",
    israel: "Израиль",
    usa: "США",
    italy: "Италия",
    spain: "Испания",
    france: "Франция",
    germany: "Германия",
    uk: "Великобритания",
    japan: "Япония",
    australia: "Австралия",
    canada: "Канада",
    switzerland: "Швейцария",
    austria: "Австрия",
    new_zealand: "Новая Зеландия",
    norway: "Норвегия",
    sweden: "Швеция",
    greece: "Греция",
    portugal: "Португалия",
    netherlands: "Нидерланды",
    belgium: "Бельгия",
    denmark: "Дания",
    ireland: "Ирландия",
    iceland: "Исландия",
    croatia: "Хорватия",
    poland: "Польша",
    czech_republic: "Чехия",
    thailand: "Таиланд",
    indonesia: "Индонезия",
    malaysia: "Малайзия",
    vietnam: "Вьетнам",
    south_korea: "Южная Корея",
    china: "Китай",
    india: "Индия",
    nepal: "Непал",
    turkey: "Турция",
    egypt: "Египет",
    morocco: "Марокко",
    south_africa: "ЮАР",
    kenya: "Кения",
    tanzania: "Танзания",
    brazil: "Бразилия",
    argentina: "Аргентина",
    chile: "Чили",
    peru: "Перу",
    mexico: "Мексика",
    costa_rica: "Коста-Рика",
    finland: "Финляндия",
    romania: "Румыния",
    hungary: "Венгрия",
    slovakia: "Словакия",
    bulgaria: "Болгария",
    serbia: "Сербия",
    slovenia: "Словения",
    montenegro: "Черногория",
    bosnia_herzegovina: "Босния",
    albania: "Албания",
    north_macedonia: "Македония",
    luxembourg: "Люксембург",
    malta: "Мальта",
    cyprus: "Кипр",
    estonia: "Эстония",
    latvia: "Латвия",
    lithuania: "Литва",

    // Regions - Israel
    north: "Север",
    center: "Центр",
    south: "Юг",
    jerusalem: "Иерусалим",
    negev: "Негев",
    eilat: "Эйлат",

    // Status
    open: "Открыто",
    full: "Заполнено",
    completed: "Завершено",
    cancelled: "Отменено",

    // Form labels
    titleHe: "Название (HE)",
    titleEn: "Название (EN)",
    descriptionHe: "Описание (HE)",
    descriptionEn: "Описание (EN)",
    selectDate: "Дата",
    selectRegion: "Регион",
    selectDifficulty: "Сложность",
    selectDuration: "Длительность",
    durationValue: "Значение",
    parentAgeRange: "Возраст родителей",
    childrenAgeRange: "Возраст детей",
    minAge: "Мин",
    maxAge: "Макс",
    uploadImage: "Загрузить",

    // Messages
    tripCreated: "Создано!",
    tripUpdated: "Обновлено!",
    joinedTrip: "Вы присоединились!",
    leftTrip: "Вы покинули!",
    tripFull: "Заполнено",
    alreadyJoined: "Уже участвуете",

    // AI
    getRecommendations: "Рекомендации",
    basedOnLocation: "По локации",
    basedOnPreferences: "По предпочтениям",
    recommendedTrips: "Рекомендации",

    // Weather
    temperature: "Температура",
    humidity: "Влажность",
    wind: "Ветер",
    conditions: "Условия",

    // Yes/No
    yes: "Да",
    no: "Нет",

    // Filters
    allRegions: "Все",
    allDifficulties: "Все",
    allDurations: "Все",
    dateRange: "Даты",
    from: "От",
    to: "До",

    // Accessibility
    wheelchair: "Коляска",
    visual_impairment: "Зрение",
    hearing_impairment: "Слух",
    mobility_aid: "Мобильность",
    stroller_friendly: "Коляска",
    elderly_friendly: "Пожилые",
    accessibilityTypes: "Доступность",
    myAccessibilityNeeds: "Мои потребности",

    // Hero
    heroTitle: "Партнеры",
    heroSubtitle: "Присоединяйтесь или создайте",
    exploreTrips: "Исследовать",
    savedTrips: "Сохраненные",

    // Empty states
    noTripsFound: "Нет",
    noSavedTrips: "Нет сохраненных",
    createFirstTrip: "Создать",
    noUpcomingTrips: "Нет",
    noOrganizedTrips: "Нет",

    // Budget
    budget: "Бюджет",
    comfortable: "Комфортно",
    luxury: "Люкс",

    // Travel companions
    solo: "Соло",
    couple: "Пара",
    family_young_kids: "Семья",
    family_teens: "Семья",
    friends: "Друзья",
    group: "Группа",

    // Activity intensity
    relaxed: "Спокойно",
    active: "Активно",
    very_active: "Очень активно",

    // Accommodation
    accommodation: "Жилье",
    camping: "Кемпинг",
    hostel: "Хостел",
    hotel: "Отель",
    boutique: "Бутик",
    resort: "Курорт",
    vacation_rental: "Аренда",
  }
  };

const detectLanguageFromLocation = async () => {
  if (typeof window === 'undefined' || !navigator.geolocation) {
    return 'he';
  }

  return new Promise((resolve) => {
    navigator.geolocation.getCurrentPosition(
      async (position) => {
        const { latitude, longitude } = position.coords;
        
        // Map coordinates to language based on region
        if (latitude >= 29 && latitude <= 33.5 && longitude >= 34 && longitude <= 36) {
          resolve('he'); // Israel
        } else if (latitude >= 41 && latitude <= 51 && longitude >= -5 && longitude <= 10) {
          // France, Spain, parts of Germany
          if (longitude >= -5 && longitude <= 3) {
            if (latitude >= 43 && latitude <= 51 && longitude >= -5 && longitude <= 5) {
              resolve('fr'); // France
            } else if (latitude >= 36 && latitude <= 44 && longitude >= -10 && longitude <= 4) {
              resolve('es'); // Spain
            } else {
              resolve('fr');
            }
          } else if (latitude >= 47 && latitude <= 55 && longitude >= 5 && longitude <= 15) {
            resolve('de'); // Germany
          } else if (latitude >= 36 && latitude <= 48 && longitude >= 6 && longitude <= 19) {
            resolve('it'); // Italy
          } else {
            resolve('he');
          }
        } else if (latitude >= 36 && latitude <= 48 && longitude >= 6 && longitude <= 19) {
          resolve('it'); // Italy
        } else if (latitude >= 47 && latitude <= 55 && longitude >= 5 && longitude <= 15) {
          resolve('de'); // Germany, Austria, Switzerland
        } else if (latitude >= 36 && latitude <= 44 && longitude >= -10 && longitude <= 4) {
          resolve('es'); // Spain
        } else if (latitude >= 41 && latitude <= 51 && longitude >= -5 && longitude <= 6) {
          resolve('fr'); // France
        } else {
          resolve('he'); // Default to Hebrew
        }
      },
      () => {
        resolve('he'); // Default to Hebrew if geolocation fails
      }
    );
  });
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved) return saved;
      return 'he'; // Default language
    }
    return 'he';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations['en']?.[key] || key;
  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}